# -*- coding: utf-8 -*-

# Controlled vocabularies.

# Natural Class category symbols.
natcat = [
    'D',
    'G',
    'N',
    'NN',
    'ND',
    'R',
    'S',
    'SUPRA',
    'T',
    'TONE',
    'TT',
    'V',
    'Vː',
    'V̆',
    'V̆̃',
    'Ṽ',
    'Ṽː',
    'Ṽ̰',
    'V̰',
    'Z',
]

# Non-nasalization process types.
proc_vocab = [
    'BN',
    'BO',
    'GN',
    'LDNH',
    'LDOH',
    'LN',
    'LNsyll',
    'LO',
    'MPP',
    'SN',
    'SO',
    'XMP',
    'XWP',
    'affricate unreleasing',
    'affrication',
    'backing',
    'bilabialization',
    'centralization',
    'consonant aspiration',
    'consonant epenthesis',
    'debuccalization',
    'degemination',
    'degliding',
    'delabialization',
    'deletion',
    'dentalization',
    'depalatalization',
    'develarization',
    'devoicing',
    'fortition',
    'fronting',
    'gemination',
    'gliding',
    'glottal constriction',
    'glottalic initiation',
    'hnasalization',
    'labialization',
    'labiodentalization',
    'lateralization',
    'lengthening',
    'lenition',
    'lowering',
    'metathesis',
    'nasal coda neutralization',
    'nasal consonant postglottalization',
    'nasal place assimilation',
    'nasal unreleasing',
    'nasalization',
    'onset fronting',
    'oral consonant postglottalization',
    'oralization',
    'palatalization',
    'PNV',
    'preservation',
    'raising',
    'representation convention',
    'restricted UR realization',
    'retroflexing',
    'rhotacization',
    'rounding',
    'semivocalization',
    'spirantization',
    'tapping',
    'tone raising',
    'total assimilation',
    'trilling',
    'UC',
    'unreleasing',
    'unrounding',
    'uvularization',
    'vocalism',
    'voicing',
    'vowel aspiration',
    'vowel epenthesis',
    'vowel shortening',
]

# Process alternation types
proc_alternation_vocab = [
    'morphological',
    'morphophonological',
    'phonological',
]
