metalang = 'English'

consonants = 'consonants'
 
bilabial = 'bilabial'
labial = 'labial'
labiodental = 'labiodental'
labio__dental = 'labio=dental'
dental = 'dental'
alveolar = 'alveolar'
post_alveolar = 'post-alveolar'
post__alveolar = 'post=alveolar'
retroflex = 'retroflex'
palatal = 'palatal'
velar = 'velar'
post_velar = 'post-velar'
pvus = 'post-velar/<br/>unspecified'
labiovelar = 'labiovelar'
labio__velar = 'labio=velar'
uvular = 'uvular'
pharyngeal = 'pharyngeal'
glottal = 'glottal'
unspe__cified = 'unspe=cified'
 
stop = 'stop'
affricate = 'affricate'
fricative = 'fricative'
nasal = 'nasal'
approximant = 'approximant'
trill = 'trill'
tap_flap = 'tap, flap'
lateral = 'lateral'
attf = 'approx./trill/tap/flap'
 
glottalized = 'glottalized'
ejective = 'ejective'
creaky = 'creaky'
plain = 'plain'
voiced = 'voiced'
aspirated = 'aspirated'
prenasalized = 'prenasalized'
implosive = 'implosive'
 
vowels = 'vowels'
 
high = 'high'
near_high = 'near high'
mid_high = 'mid-high'
mid = 'mid'
mid_low = 'mid-low'
near_low = 'near low'
low = 'low'
 
front = 'front'
central = 'central'
back = 'back'
 
unrounded = 'unrounded'
rounded = 'rounded'
 
suprasegmental = 'suprasegmental'
tone = 'tone'
laryngeal_harmony = 'laryngeal harmony'
nasal_harmony = 'nasal harmony'
 
other_names = 'other names'
geographical_location = 'geographical location'
location = 'location'
language_code = 'language code'
family = 'family'
notes = 'notes'
bibliography = 'bibliography'
 
map = 'map'
