metalang = 'Español'
 
consonants = 'consonantes'
 
bilabial = 'bilabial'
labial = 'labial'
labiodental = 'labiodental'
labio__dental = 'labio=dental'
dental = 'dental'
alveolar = 'alveolar'
post-alveolar = 'post-alveolar'
post__alveolar = 'post=alveolar'
retroflex = 'retrofleja'
palatal = 'palatal'
velar = 'velar'
post-velar = 'post-velar'
pvus = 'post-velar/<br/>no especificada'
labiovelar = 'labiovelar'
labio=velar = 'labio=dental'
uvular = 'uvular'
pharyngeal = 'faringeal'
glottal = 'glotal'
unspe__cified = 'no espe=cificada'
 
stop = 'oclusiva'
affricate = 'africada'
fricative = 'fricativa'
nasal = 'nasal'
approximant = 'aproximante'
trill = 'vibrante multiple'
tap_flap = 'vibrante simple'
lateral = 'lateral'
attf = 'approx./vibrante'
 
glottalized = 'glotalizada'
ejective = 'eyectiva'
creaky = 'laringealizada'
plain = 'sorda'
voiced = 'sonora'
aspirated = 'aspirada'
prenasalized = 'prenasalizada'
implosive = 'implosiva'
 
vowels = 'vocales'
 
high = 'cerrada'
near_high = 'casi cerrada'
mid_high = 'semicerrada'
mid = 'intermedia'
mid_low = 'semiabierta'
near_low = 'casi abierta'
low = 'abierta'
 
front = 'anterior'
central = 'central'
back = 'posterior'
 
unrounded = 'no redondeada'
rounded = 'redondeada'
 
suprasegmental = 'suprasegmental'
tone = 'tono'
laryngeal harmony = 'armonía laringeal'
nasal harmony = 'armonía nasal'
 
other_names = 'otros nombres'
geographical_location = 'localización geográfica'
location = 'localización'
language_code = 'código de lengua'
family = 'familia'
notes = 'notas'
bibliography = 'bibliografía'
 
map = 'mapa'
