metalang = 'Português'

consonants = 'consoantes'

bilabial = 'bilabial'
labial = 'labial'
labiodental = 'labiodental'
labio__dental = 'labio=dental'
dental = 'dental'
alveolar = 'alveolar'
post-alveolar = 'pós-alveolar'
post=alveolar = 'pós=alveolar'
retroflex = 'retroflexa'
palatal = 'palatal'
velar = 'velar'
post_velar = 'pós-velar'
pvus = 'pós-velar/<br/>não especificada'
labiovelar = 'labiovelar'
labio__velar = 'labio=dental'
uvular = 'uvular'
pharyngeal = 'faringal'
glottal = 'glotal'
unspe__cified = 'não espe=cificada'

stop = 'oclusiva'
affricate = 'africada'
fricative = 'fricativa'
nasal = 'nasal'
approximant = 'aproximante'
trill = 'vibrante multiple'
tap_flap = 'vibrante simple'
lateral = 'lateral'
attf = 'approx./vibrante'

glottalized = 'glotalizada'
ejective = 'ejectiva'
creaky = 'laringealizada'
plain = 'surda'
voiced = 'sonora'
aspirated = 'aspirada'
prenasalized = 'pré-nasal'
implosive = 'implosiva'

vowels = 'vogais'

high = 'fechada/alta'
near_high = 'quase fechada'
mid_high = 'semifechada'
mid = 'média'
mid_low = 'semiaberta'
near_low = 'quase aberta'
low = 'aberta/baixa'

front = 'anterior'
central = 'central'
back = 'posterior'

unrounded = 'não arredondada'
rounded = 'arredondada'

suprasegmental = 'suprasegmental'
tone = 'tom'
laryngeal_harmony = ' harmonia laringeal'
nasal_harmony = 'harmonia nasal'

other_names = 'outros nomes'
geographical_location = 'localização geográfica'
location = 'localização'
language_code = 'código de língua'
family = 'família'
notes = 'notas'
bibliography = 'bibliografia'

map = 'mapa'
